In [1]:
import cv2
import numpy as np

In [10]:
doc = cv2.imread("note_detection.jpg")


#Step 1 Resize the image to desired size
doc = cv2.resize(doc,(600,400))
original = doc.copy()









In [11]:
#Step2 Convert the image to greyscale
doc = cv2.cvtColor(doc,cv2.COLOR_BGR2GRAY)
# cv2.imshow("Grayscale",doc)
# cv2.waitKey(0)
# cv2.destroyAllWindows()


In [12]:
#Step3 Apply Gaussian blur for better edge detection
doc = cv2.GaussianBlur(doc,(5,5),0)
# cv2.imshow("GuassianBlur",doc)
# cv2.waitKey(0)
# cv2.destroyAllWindows()

In [13]:
#Step 4 Apply canny filter
canny = cv2.Canny(doc,100,120)
# cv2.imshow("Canny",canny)
# cv2.waitKey(0)
# cv2.destroyAllWindows()

In [14]:
#Step5 Drawing countour boundary
contours,heriarchy = cv2.findContours(canny,cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_NONE)

print("Countours found are : " +str(len(contours)))

# Draw all contours
# Use '-1' as the 3rd parameter to draw all
cv2.drawContours(original, contours, -1, (255,0,0), 3)
cv2.imshow('Contours', original)
cv2.waitKey(0)
cv2.destroyAllWindows()

Countours found are : 14


In [15]:
contours

[array([[[ 28, 393]],
 
        [[ 28, 394]],
 
        [[ 29, 395]],
 
        [[ 30, 395]],
 
        [[ 31, 395]],
 
        [[ 32, 395]],
 
        [[ 33, 396]],
 
        [[ 34, 396]],
 
        [[ 35, 396]],
 
        [[ 36, 397]],
 
        [[ 37, 397]],
 
        [[ 38, 398]],
 
        [[ 39, 398]],
 
        [[ 38, 397]],
 
        [[ 37, 397]],
 
        [[ 36, 396]],
 
        [[ 35, 396]],
 
        [[ 34, 396]],
 
        [[ 33, 396]],
 
        [[ 32, 395]],
 
        [[ 31, 395]],
 
        [[ 30, 395]],
 
        [[ 29, 394]]], dtype=int32),
 array([[[ 31, 392]],
 
        [[ 32, 393]],
 
        [[ 33, 393]],
 
        [[ 32, 392]]], dtype=int32),
 array([[[ 15, 389]],
 
        [[ 16, 389]],
 
        [[ 17, 389]],
 
        [[ 18, 390]],
 
        [[ 19, 390]],
 
        [[ 20, 391]],
 
        [[ 21, 391]],
 
        [[ 20, 391]],
 
        [[ 19, 390]],
 
        [[ 18, 390]],
 
        [[ 17, 389]],
 
        [[ 16, 389]]], dtype=int32),
 array([[[307, 360]]], dt

In [1]:
#Corner detection using Good features to track is a better corner detection algorithm
import cv2
import numpy as np
img = cv2.imread('note_detection.jpg')
img= cv2.resize(img,(800,600))
gray = cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)

# Specify top 10 corners
corners = cv2.goodFeaturesToTrack(gray, 10, 0.01, 150)

for corner in corners:
    x, y = corner[0]
    x = int(x)
    y = int(y)
    cv2.rectangle(img,(x-10,y-10),(x+10,y+10),(0,255,0), 2)
    
cv2.imshow("Corners Found", img)
cv2.waitKey()
cv2.destroyAllWindows()
