In [47]:
import cv2
import numpy as np

In [68]:
#Load the Haar Cascade classifiers
face_classifier = cv2.CascadeClassifier('Haarcascades/haarcascade_frontalface_default.xml')
eye_classifier = cv2.CascadeClassifier('Haarcascades/haarcascade_eye.xml')

img = cv2.imread('team_face.jpg')
y,x,c = img.shape
# cv2.imshow('Image',img)
# cv2.waitKey(0)
# cv2.destroyAllWindows()

In [69]:
#convert image to gray scale 
gray = cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)

In [70]:
#Detect the face popsitions
faces = face_classifier.detectMultiScale(gray,1.1,10)
#Faces produce an array of vectors for each rectangle where a face is detected 
print (faces)


[[641 115  98  98]
 [ 80 464  99  99]
 [677 397  83  83]
 [301 238  90  90]
 [521 497  99  99]
 [935 231 105 105]
 [ 68 167 101 101]
 [320 461 102 102]
 [515 271  87  87]]


In [71]:
for (x,y,w,h) in faces:
    cv2.rectangle(img,(x+20,y+20),(x+w,y+h),(0,255,0),3)
    cv2.putText(img, 'Face', (x, y-10), cv2.FONT_HERSHEY_SIMPLEX, 0.9, (36,255,12), 2)


cv2.imshow("Image",img)
cv2.waitKey(0)      
cv2.destroyAllWindows()